### ISSUE TITLE
Description of WeGA-WebApp-lib release 1.3.0

### ISSUE THREAD

**Issue by bwbohl** [Edirom/WeGA-WebApp-lib#3]
The following functions have changed, too I think:

* printDate

While the following worked in 1.2.0:
```query
date:printDate($death/tei:date, 'de', function(){'month'} , function(){'[D]. [MNn] [Y]'})
```

1.3.0 only accepts

```xquery
date:printDate($birth/tei:date, 'de', function(){'month'} , $config:default-date-picture-string)
```

**Comment by peterstadler** [comment]
Yes, you're right. The change happened in 6ec450a7498d74a6bbcc9ade4f6daea26aec5db2 and since then the last parameter is expected to be a function reference taking one argument. The additional argument is crucial, so changing your first example to 
```xquery
date:printDate($death/tei:date, 'de', function(){'month'} , function($someparam){'[D]. [MNn] [Y]'})
```
should work.

**Comment by peterstadler** [comment]
Updated the release notes at https://github.com/Edirom/WeGA-WebApp-lib/releases/tag/v1.3.0

Does that fix it for you?

**Comment by bwbohl** [comment]
works perfectly, thanks ;-)

**Comment by peterstadler** [comment]
Thanks for the heads up :)
