### ISSUE TITLE
why do version numbers diverge

### ISSUE THREAD

**Issue by bwbohl** [Edirom/WeGA-WebApp-lib#4]
why is the project.version in develop 1.3.1 while on master it is 1.3.0?

**Comment by peterstadler** [comment]
master always reflects the latest release; the project.version in development is then bumped after a release—and will be merged into master for the next release.
I hope it's more or less compliant with "[mainline development](https://gitversion.readthedocs.io/en/latest/reference/mainline-development/)"?!

**Comment by bwbohl** [comment]
ok interesting, I never bump before issuing a new release, as one might never knows which server the next release will have. I alway follow the workflow described here: https://nvie.com/posts/a-successful-git-branching-model/
