### ISSUE TITLE
RFC 822 compliance

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp-lib#6]
Thanks @bwbohl for adding the `date:rfc822()` function! 
While I was going to add some tests (yay, always add tests!) I came across two edge cases:

* one digit days: while it is allowed by the [specs](http://www.faqs.org/rfcs/rfc822.html) and [works in practice](https://groups.yahoo.com/neo/groups/rss-public/conversations/topics/536), I still wonder whether we should add a leading zero since [most examples](https://validator.w3.org/feed/docs/warning/ProblematicalRFC822Date.html) feature two digit days?
* `xs:dateTime` allows for missing timezone information ([nice thread here](https://stackoverflow.com/questions/22518217/semantics-of-the-xsddatetime-without-timezone-and-its-conversion-to-date)) but RFC 822 needs that information, right? Shall we just turn it into `+0000`?

**Comment by bwbohl** [comment]
Wow testing sounds like a good plan, unfortunately I only tested with current-dateTime und unluckily today was a two digit day and my timezone info was there…

I think, both your suggestions are a good way to go ;-) thanks for fixing
