### ISSUE TITLE
wega-util-shared:has-content fails on xs:date

### ISSUE THREAD

**Issue by bwbohl** [Edirom/WeGA-WebApp-lib#8]
the function `wega-util-shared:has-content` 
https://github.com/Edirom/WeGA-WebApp-lib/blob/63e99f26bec75c3efe1bb5cc49ad4c260e32f644/xquery/wega-util-shared.xqm#L29
fails on xs:date input with

```err:FORG0006 effective boolean value invalid operand type: xs:date```

the functions applies the default return `boolean($item)` this could be fixed by modifying 
https://github.com/Edirom/WeGA-WebApp-lib/blob/63e99f26bec75c3efe1bb5cc49ad4c260e32f644/xquery/wega-util-shared.xqm#L40
to:
```
default return boolean(string($date))
```

or by introducing a new test:

```case xs:date return boolean(string($date))

**Comment by peterstadler** [comment]
but I addressed this already in https://github.com/Edirom/WeGA-WebApp-lib/commit/63e99f26bec75c3efe1bb5cc49ad4c260e32f644 -- as a fix for https://github.com/baz-ga/bazga-webapp/issues/31 ?!
